linters:
  rubocop:
    display_cop_names: true
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "spec/*helper.rb"
    - "config/environments/*.rb"
fixers:
   enable: true